### PR TITLE
BB-10: Implement Enemy line of sight

### PR DESCRIPTION
**Pull request by emily-penna**
Added Field of view using ray casts. Enter debug mode to see the individual rays.
Methods in place to check if a specific object is seen have yet to be thoroughly tested.

### CODE REVIEW

**Review by sophiahxu — CHANGES_REQUESTED** [review]
Were the .idea and gradle library changes intentional? I can't really tell so I'm just gonna request a review on it since idk if it would mess stuff up

**Comment by agettig** [comment]
I think we probably don't need the .idea folder. We can add it to the .gitignore

**Comment by emily-penna** [comment]
I'm checking with Caroline right now, but I don't think we changed either of those files.

**Comment by agettig** [comment]
I think it looks good! In DudeModel.activatePhysics, vision.test(world) is commented out, is that just old and not used anymore?
Do we want to add this to enemies now? And is anything implemented for detecting the player? It looks like we can use Vision.canSee but it hasn't been used yet.

**Review by agettig — CHANGES_REQUESTED** [review]
Remove .idea files

**Pull request merged**
